CREATE TABLE titlebasics (
 tconst VARCHAR2(255) PRIMARY KEY,
 titletype VARCHAR2(255) NOT NULL,
 primarytitle VARCHAR2(255) NOT NULL,
 originaltitle VARCHAR2(255) NOT NULL,
 isAdult VARCHAR2(1) NOT NULL,
 startyear YEAR NOT NULL,
 endyear YEAR,
 runtimeminutes INT NOT NULL,
 genres VARCHAR2(255) NOT NULL
);

CREATE TABLE names (
  nconst VARCHAR2(255) PRIMARY KEY,
  primaryname VARCHAR2(255) NOT NULL,
  birthyear YEAR NOT NULL,
  deathyear YEAR,
  primaryprofession VARCHAR2(1024) NOT NULL,
  knownfortitles VARCHAR2(1024) NOT NULL
);


INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0072890','movie','Dog Day Afternoon','Dog Day Afternoon','0',1975,null,125,'Biography,Crime,Drama');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0070666','movie','Serpico','Serpico','0',1973,null,130,'Biography,Crime,Drama');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0068646','movie','The Godfather','The Godfather','0',1972,null,175,'Crime,Drama');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0099422','movie','Dick Tracy','Dick Tracy','0',1990,null,105,'Action,Comedy,Crime');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0327056','movie','Mystic River','Mystic River',0,2003,null,138,'Crime,Drama,Mystery');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0361127','movie','The Woodsman','The Woodsman',0,2004,null,87,'Drama');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0164052','movie','Hollow Man','Hollow Man',0,2000,null,112,'Action,Horror,Sci-Fi');
INSERT INTO titlebasics(TCONST, TITLETYPE, PRIMARYTITLE, ORIGINALTITLE, ISADULT, STARTYEAR, ENDYEAR, RUNTIMEMINUTES, GENRES)
VALUES ('tt0087277','movie','Footloose','Footloose',0,1984,null,107,'Music,Romance');


INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000199','Al Pacino',1940,null,'actor,producer,soundtrack','tt0072890,tt0070666,tt0068646,tt0099422');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000008','Marlon Brando',1924,2004,'actor,soundtrack,director','tt0044081,tt0068646,tt0070849,tt0078788');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000102','Kevin Bacon',1958,null,'actor,producer,soundtrack','tt0327056,tt0361127,tt0164052,tt0087277');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000989','One',1958,null,'actor','tt0327056,tt111');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000990','Two',1958,null,'actor','tt222,tt111');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000991','Three',1958,null,'actor','tt333,tt222');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000992','Four',1958,null,'actor','tt444,tt333');

INSERT INTO names(NCONST, PRIMARYNAME, BIRTHYEAR, DEATHYEAR, PRIMARYPROFESSION, KNOWNFORTITLES)
VALUES('nm0000993','Five',1958,null,'actor','tt555,tt444');
